### ISSUE TITLE
关于episode_novel_dataloader的问题

### ISSUE THREAD

**Issue by dongdongqiangcsust** [lovelyqian/AMeFu-Net#10]
关于episode_novel_dataloader中的这一行
video, video_depth = get_video_fusion_from_video_info_rgb_depth_object_multi_depth(video_info..)
这个函数episode_novel_dataloader，输入的是class_name
而utils.py文件中定义的 
get_video_fusion_from_video_info_rgb_depth_object_multi_depth
video_info接受的输入应该是”class_name/video_name"
请问dataload中如何完成对视频样本的采样的

**Comment by SilverBach805** [comment]
> 关于episode_novel_dataloader中的这一行 video, video_depth = get_video_fusion_from_video_info_rgb_depth_object_multi_depth(video_info..) 这个函数episode_novel_dataloader，输入的是class_name 而utils.py文件中定义的 get_video_fusion_from_video_info_rgb_depth_object_multi_depth video_info接受的输入应该是”class_name/video_name" 请问dataload中如何完成对视频样本的采样的

请问你解决了吗，我也碰到了这个问题，希望能和你交流一下。
